### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#1]
This is a purely aesthetic comment: consider using roslint or another automated style checker for following a consistent code style.

There are some places where you have two function names that are essentially the same but have the different style, e.g. scaleModel vs. scale_model, and one is a helper function of the other. I think it would be preferred to have consistent style and slightly more descriptive names, like scaleModel and scaleModelRecursive.

I noticed that some lines run particularly long, often because there's a comment inline, e.g.

```
int dof_index; ///< index of this dh-parameter in the list of DOF specifications of graspit! (or can be used otherwise if used for another package)
```

Also, remove extraneous commented lines of code and dead code that is blocked off with `#if 0`.

**Comment by JenniferBuehler** [comment]
Good point, I forgot to check the code for such things. Thanks.
