### ISSUE TITLE
[grasp_planning_graspit] Catkin dependency

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#13]
Can the catkin dependency be optional? I get a CMake error when I try to build the package the pure CMake way without my ROS setup.bash sourced.

It should be as simple as removing REQUIRED from the `find_package(catkin)` invocation in CMakeLists.txt, and adding conditional logic, e.g. `if(catkin_FOUND)` for all catkin-specific stuff...

**Comment by JenniferBuehler** [comment]
I was just going to do that today ;)
