### ISSUE TITLE
TODOs and future plans peppered through code/docs

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#16]
In the documentation for `GraspPlanner`, 

```
At this stage, only support simmulated annealing planning types is offered. "Loop" and "multi-threaded" can probably be integrated fairly easy.
```

Consider finding places like this in the documentation or "todos" in the code and adding Github issues for them, so that all the future work and extensions are consolidated in one place, e.g. add an issue for "integrating Loop and Multi-threaded planning types"

**Comment by JenniferBuehler** [comment]
Good idea. I have a TODO.md already in the repo, but creating github issues for the main things is better.
For the little things in the list that I'm going to do over the next days, it's probably not worth it.

I'd leave the comment(s) in the class header documentation(s) however, so people who don't read READMEs or github issues can see what's supported and what not as well.

**Comment by JenniferBuehler** [comment]
I've moved important issues from the TODO.md into git issues. 
I  also removed the description of issues at various places through the README files and the class headers. However I've left *some* comments in class headers where I thought it's appropriate, so that it also gets into the doxygen API.
