### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#2]
Related to style, but has some functional utility as well:

Consider putting the functions in urdf2graspit/Helpers.h in a namespace, e.g.

```
namespace urdf2graspit {
  namespace helpers {
    extern void resetStdOut();
    ...
  }
}
```

You could also consider putting everything in the urdf2graspit package in the `urdf2graspit` namespace. This is to prevent naming collisions with public members from other packages.

Same applies for XmlFuncs.h.

**Comment by JenniferBuehler** [comment]
Yes I've been wanting to do this. Will be fixed in the next commit.
