### ISSUE TITLE
Macros and #defines

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#3]
Think about when you want to use a #define vs. a parameter vs. a public const member. There are a lot of places where you use #define for something that you might want to vary in the future.

For example in Urdf2Graspit.h, many of the hardcoded #define constants are actually things that the user might want to enter via the command line or rosparams: https://github.com/JenniferBuehler/jb-ros-packs/blob/master/urdf2graspit/include/urdf2graspit/Urdf2Graspit.h#L17

Specifying these as parameters would be a "nice to have" feature that isn't necessary for the package, but makes it more usable.

**Comment by JenniferBuehler** [comment]
Yes that's true, I usually change this after the initial development stage when I tidy up the things needed or not. Will update this in next commit.

**Comment by JenniferBuehler** [comment]
I have parameterized everything that makes sense and added the parameters as command line argument or ros parameter. Also added launch files incl. one for the example setting of the jaco hand.
