### ISSUE TITLE
Error reporting/debug output

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#5]
You seem to mostly use ROS_ERROR/ROS_WARN for reporting errors and ROS_INFO for general information, but you also occasionally print to std::cout and std::cerr. Pick one and roll with it.

**Comment by JenniferBuehler** [comment]
Huh, I usually only use ROS_* functions to print... I must have slipped at a few places then. Thanks for pointing this out.
