### ISSUE TITLE
Casting

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#6]
Make sure to check if the pointer is NULL after casting a pointer. Also, avoid using c-style casts. You do a lot of casting in MarkerSelector, and you check in line 169-172, which is good, but in the function `MarkerSelector` you cast pointers a few times and don't check the pointer afterwards.

**Comment by JenniferBuehler** [comment]
Yes sometimes when I'm sure the right type is always passed anyway (and it's a private function) I retreat to c-style casts, I know it's not good, pure laziness. Will find the places where this happened and do static/dynamic casts only. Thanks for pointing this out.
