### ISSUE TITLE
Pass vectors instead of 3 floats

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#7]
There are a few functions (particularly in MarkerSelector) where you pass float x, float y, float z. Using Eigen 3-vectors would shrink the size of these call signatures.

**Comment by JenniferBuehler** [comment]
Good point. It's a remnant of me switching between different math libs, and for such simple functions, dependencies to a certain library can be easily avoided. Sometimes, the x/y/z values are not available in a vector3d to start with, and I find it a bit awkward to create a new object just to pass a parameter.

On the other hand, if the vector is already available, it's necessary to call the individual getter functions to pass the parameters. That's not pretty either.

It's a bit of a trade-off. I'll look through the code again and find where this is done. Maybe it's better to change the parameters as you suggested.
